server:
  port: 8081
spring:
  application:
    name: customer
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/user
    username: dbuser
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true